spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usecasedb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug